#
# weechat -- sec.conf
#
# WARNING: It is NOT recommended to edit this file by hand,
# especially if WeeChat is running.
#
# Use commands like /set or /fset to change settings in WeeChat.
#
# For more info, see: https://weechat.org/doc/weechat/quickstart/
#

[crypt]
cipher = aes256
hash_algo = sha256
passphrase_command = ""
salt = on

[data]
__passphrase__ = on
freenode_pass = "DFC1ADACAA0AA39296BC91B101623A8443B533130926B99C2DF5A036C3F58C194D07F28F491F606C5F25DEF0583F25"
dlnet_pass = "1604D67F5D927A56DD1FB4A2E718D3F851B152F9DD24F68798480100E694FECC236D8EB9A617C502DE085E3F84B04C"
